version: "2"

linters:
  enable:
    - gosec
    - misspell
    - bodyclose
    - durationcheck
    - errname
    - nilerr
    - unconvert
    - unparam
    - gocritic

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
